services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_test
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=pass123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./BD/init.sql:/tmp/init.sql
    networks:
      - red-test
    deploy:
      resources:
        limits:
          memory: 2048M

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./BD/init.sql:/tmp/BaseDatos.sql
    entrypoint: >
      /bin/bash -c "
      sleep 40 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P pass123! -i /tmp/BaseDatos.sql
      "
    networks:
      - red-test

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - red-test

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - red-test

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # --- microservice #1 ---
  ms-customers:
    build: ./ms-customers
    container_name: ms-customers
    environment:
      DB_HOST: sqlserver
      DB_PASSWORD: pass123!
      SPRING_PROFILES_ACTIVE: prd
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver
      - redis
    networks:
      - red-test

  # --- microservice #2 ---
  ms-accounts:
    build: ./ms-accounts
    container_name: ms-accounts
    environment:
      DB_HOST: sqlserver
      DB_PASSWORD: pass123!
      SPRING_PROFILES_ACTIVE: prd
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8082:8080"
    depends_on:
      - sqlserver
    networks:
      - red-test

  # --- microservice #3 ---
  ms-token:
    build: ./ms-token
    container_name: ms-token
    environment:
      DB_HOST: sqlserver
      DB_PASSWORD: pass123!
      SPRING_PROFILES_ACTIVE: prd
    ports:
      - "8083:8080"
    networks:
      - red-test

networks:
  red-test:
    driver: bridge

volumes:
  redis_data: