spring:
  datasource:
    url: ${data.jdbcUrl}
    username: sa
    password: ${DB_PASSWORD:pass123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      auto-create: true
  redis:
    host: localhost
    port: 6379
    password: pass123!
    timeout: 60000

api:
  jwt: ${host.url.token}/api/token
  customer: ${host.url.customer}/api/clientes/search