spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key: ${SECRET_PUBLIC_KEY}
  datasource:
    url: ${data.jdbcUrl}
    username: sa
    password: ${DB_PASSWORD:pass123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ms-customers-group
      auto-offset-reset: earliest
    listener:
      ack-mode: record
