data:
  jdbcUrl: jdbc:sqlserver://${DB_HOST}:1433;databaseName=db_customers;encrypt=true;trustServerCertificate=true


SECRET_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1ilA7G25cVPTlId7PdVXsCALp30SNgxs36+jHOdn29lYd97sUa8aupMPdPSpk55rpyY/bzfdO2zoTeoAyKJ92ch2n4AQ3O+8t2BAKsT88V0EIqT5M5P7QqwusVovk3+rFm7TklgPueRNEsGF6hBqtjnk+fUKqFAA1RjsSgh730DM6iGNTjzOwmbli9uQoKVlaJTSJwMJaMZknGQh7PGMjXPBUdm7MkZJt+KjZ1nxjZ52j5fNgEljW6JacJee+j8FkDC0NDBsNUPHDSWR2/v054S0A69OKUoyPtfiRA2kvY6p+2YYv42odZFMTGdcpu0QTP83Euj/cf1BqmbcJ8dJIwIDAQAB
