jwt:
  private-key: ${SECRET_PRIVATE_KEY}
  public-key: ${SECRET_PUBLIC_KEY}
  expiration: 3600000 # 5 minutes
  issuer: https://ms-token/jwt
  audience:
    - ms-accounts
    - ms-movements
    - ms-customers
  secret: ${SECRET_CLIENT}